apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: tostada
build:
  artifacts:
    - image: tostada
      docker:
        dockerfile: Dockerfile
manifests:
  helm:
    releases:
      - name: tostada
        chartPath: charts/tostada
        namespace: tostada
        createNamespace: true
        valuesFiles:
          - charts/tostada/values-local.yaml
deploy:
  kubectl:
    defaultNamespace: tostada
