apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: tostada
build:
  artifacts:
    - image: tostada
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - k8s/oidc-mock.yaml
    - k8s/guacamole.yaml
    - k8s/tostada.yaml
  helm:
    releases:
      - name: jupyterhub
        remoteChart: jupyterhub
        repo: https://hub.jupyter.org/helm-chart/
        version: 4.1.0
        namespace: tostada
        createNamespace: true
        valuesFiles:
          - k8s/jupyterhub-values.yaml
deploy:
  kubectl:
    defaultNamespace: tostada
