apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: tostada
build:
  artifacts:
    - image: tostada
      docker:
        dockerfile: Dockerfile
        buildArgs:
          DEVELOPMENT: "1"
deploy:
  helm:
    releases:
      - name: tostada
        chartPath: charts/tostada
        namespace: tostada
        createNamespace: true
        setValueTemplates:
          tostada.image.registry: "{{.IMAGE_DOMAIN_tostada}}"
          tostada.image.repository: "{{.IMAGE_REPO_NO_DOMAIN_tostada}}"
          tostada.image.tag: "{{.IMAGE_TAG_tostada}}"
