apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
  namespace: tostada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
        - name: guacd
          image: guacamole/guacd:1.6.0
          ports:
            - containerPort: 4822
        - name: guacamole
          image: guacamole/guacamole:1.6.0
          ports:
            - containerPort: 8080
          env:
            - name: GUACD_HOSTNAME
              value: "localhost"
            - name: GUACD_PORT
              value: "4822"
            - name: JSON_SECRET_KEY
              value: "8bea5deb816809f814b83c28cf14d3e2"
            - name: WEBAPP_CONTEXT
              value: "ROOT"
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
  namespace: tostada
spec:
  selector:
    app: guacamole
  ports:
    - port: 8080
      targetPort: 8080
