apiVersion: apps/v1
kind: Deployment
metadata:
  name: tostada
  namespace: tostada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tostada
  template:
    metadata:
      labels:
        app: tostada
    spec:
      containers:
        - name: tostada
          image: tostada
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: tostada
  namespace: tostada
spec:
  selector:
    app: tostada
  ports:
    - port: 8080
      targetPort: 8080
