apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
        - name: guacd
          image: {{ .Values.guacamole.guacd.image }}
          ports:
            - containerPort: 4822
        - name: guacamole
          image: {{ .Values.guacamole.web.image }}
          ports:
            - containerPort: 8080
          env:
            - name: GUACD_HOSTNAME
              value: "localhost"
            - name: GUACD_PORT
              value: "4822"
            - name: JSON_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: guacamole-json-secret-key
            - name: WEBAPP_CONTEXT
              value: "ROOT"
---
apiVersion: v1
kind: Service
metadata:
  name: guacamole
spec:
  selector:
    app: guacamole
  ports:
    - port: 8080
      targetPort: 8080
