apiVersion: apps/v1
kind: Deployment
metadata:
  name: tostada
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tostada
  template:
    metadata:
      labels:
        app: tostada
        hub.jupyter.org/network-access-hub: "true"
        hub.jupyter.org/network-access-singleuser: "true"
      annotations:
        checksum/config: {{ include (print .Template.BasePath "/tostada-configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: tostada
          image: {{ .Values.tostada.image }}
          imagePullPolicy: {{ .Values.tostada.imagePullPolicy }}
          ports:
            - containerPort: 8080
          env:
            - name: OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: oidc-client-secret
            - name: GUACAMOLE_JSON_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: guacamole-json-secret-key
            - name: JUPYTERHUB_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.existingSecret }}
                  key: hub.services.tostada.apiToken
          volumeMounts:
            - name: config
              mountPath: /etc/tostada
            - name: data
              mountPath: /data
      volumes:
        - name: config
          configMap:
            name: tostada-config
        - name: data
          persistentVolumeClaim:
            claimName: tostada-data
---
apiVersion: v1
kind: Service
metadata:
  name: tostada
spec:
  selector:
    app: tostada
  ports:
    - port: 8080
      targetPort: 8080
