apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tostada-data
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.tostada.persistence.storageClass }}
  storageClassName: {{ .Values.tostada.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.tostada.persistence.size }}
